### PR TITLE
Update plugin to use semantic versioning

### PR DESCRIPTION
**Pull request by amayvs**
This PR makes it compatible to use with [cordova-check-plugins](https://github.com/dpa99c/cordova-check-plugins).

Let me know if you want to bump the version to `1.0.1`.

### CODE REVIEW

**Comment by ziyaddin** [comment]
@tomloprod please bump the version to `1.0.1`. NPM package is still broken due to invalid versioning.

**Comment by tomloprod** [comment]
@ziyaddin Done. Try it now, please.

Thanks.

**Comment by ziyaddin** [comment]
@tomloprod Thank you! Are you sure you published `1.0.1` to NPM too?

image

**Comment by tomloprod** [comment]
@ziyaddin Sorry, forgot to publish. Now its available. Thank you!

**Comment by ziyaddin** [comment]
@tomloprod You are welcome!

**Pull request merged**
